name = "DualMemoryABM"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1.9"
StatsBase = "0.33, 0.34"
JLD2 = "0.4, 0.5"
CSV = "0.10"
Tables = "1"
